# Generated by Django 5.2.4 on 2025-07-16 23:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=200, verbose_name='会话名称')),
                ('total_words', models.IntegerField(default=0, verbose_name='总单词数')),
                ('completed_words', models.IntegerField(default=0, verbose_name='已完成单词数')),
                ('correct_count', models.IntegerField(default=0, verbose_name='正确数量')),
                ('wrong_count', models.IntegerField(default=0, verbose_name='错误数量')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('word_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.wordlist', verbose_name='单词列表')),
            ],
            options={
                'verbose_name': '听写会话',
                'verbose_name_plural': '听写会话',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='DictationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=100, verbose_name='用户答案')),
                ('is_correct', models.BooleanField(verbose_name='是否正确')),
                ('attempt_count', models.IntegerField(default=1, verbose_name='尝试次数')),
                ('time_taken', models.FloatField(default=0, verbose_name='用时(秒)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.word', verbose_name='单词')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictation.dictationsession', verbose_name='听写会话')),
            ],
            options={
                'verbose_name': '听写记录',
                'verbose_name_plural': '听写记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.IntegerField(default=0, verbose_name='总尝试次数')),
                ('correct_attempts', models.IntegerField(default=0, verbose_name='正确次数')),
                ('last_practiced', models.DateTimeField(blank=True, null=True, verbose_name='最后练习时间')),
                ('mastery_level', models.IntegerField(choices=[(0, '未掌握'), (1, '初步掌握'), (2, '基本掌握'), (3, '熟练掌握'), (4, '完全掌握')], default=0, verbose_name='掌握程度')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.word', verbose_name='单词')),
            ],
            options={
                'verbose_name': '用户进度',
                'verbose_name_plural': '用户进度',
                'unique_together': {('word',)},
            },
        ),
    ]
