# Generated by Django 5.2.4 on 2025-07-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0002_alter_dictationrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictationsession',
            name='skipped_words',
            field=models.TextField(blank=True, default='', verbose_name='跳过的单词ID列表'),
        ),
    ]
