# Generated by Django 5.2.4 on 2025-07-16 23:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='单词')),
                ('phonetic', models.CharField(blank=True, max_length=100, verbose_name='音标')),
                ('translation', models.TextField(verbose_name='中文释义')),
                ('example_sentence', models.TextField(blank=True, verbose_name='例句')),
                ('difficulty_level', models.IntegerField(choices=[(1, '简单'), (2, '中等'), (3, '困难')], default=1, verbose_name='难度等级')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '单词',
                'verbose_name_plural': '单词',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='列表名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '单词列表',
                'verbose_name_plural': '单词列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WordListWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.word', verbose_name='单词')),
                ('word_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.wordlist', verbose_name='单词列表')),
            ],
            options={
                'verbose_name': '单词列表项',
                'verbose_name_plural': '单词列表项',
                'ordering': ['order'],
                'unique_together': {('word_list', 'word')},
            },
        ),
        migrations.AddField(
            model_name='wordlist',
            name='words',
            field=models.ManyToManyField(through='vocabulary.WordListWord', to='vocabulary.word', verbose_name='单词'),
        ),
    ]
