# Generated by Django 5.2.4 on 2025-07-17 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('plan_type', models.CharField(choices=[('NEW', '新学习'), ('REVIEW', '复习计划')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.wordlist')),
            ],
        ),
        migrations.CreateModel(
            name='WordLearningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_learn_date', models.DateTimeField(auto_now_add=True)),
                ('last_review_date', models.DateTimeField(auto_now=True)),
                ('review_count', models.IntegerField(default=0)),
                ('mastery_level', models.IntegerField(default=0)),
                ('next_review_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.word')),
            ],
            options={
                'unique_together': {('word', 'user')},
            },
        ),
    ]
