# Generated by Django 5.2.4 on 2025-07-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_reviewplan_wordlearningrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=100, verbose_name='单词'),
        ),
    ]
